<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>md-icon</name>
   <tag></tag>
   <elementGuidId>32946736-c5f0-46d2-8d38-e458d78a8421</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//md-dialog-content[@id='dialogContent_correspondence-workflow-popup']/div/div/md-content/div/div/div[3]/md-card/md-table-container/table/tbody/tr/td[7]/div/vertical-menu-workflow-item-directive/div/button/md-icon</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.md-icon-button.md-button.md-ink-ripple.md-focused > md-icon</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;dialogContent_correspondence-workflow-popup&quot;)/div[1]/div[@class=&quot;layout-row flex&quot;]/md-content[@class=&quot;relative scrollable-element ps ps--theme_default _md layout-row flex&quot;]/div[@class=&quot;p20&quot;]/div[@class=&quot;layout-column flex&quot;]/div[@class=&quot;layout-row&quot;]/md-card[@class=&quot;card-overlay _md layout-column flex&quot;]/md-table-container[1]/table[@class=&quot;ng-pristine ng-untouched ng-valid md-table ng-not-empty md-row-select&quot;]/tbody[@class=&quot;md-body&quot;]/tr[@class=&quot;md-row&quot;]/td[@class=&quot;md-cell&quot;]/div[@class=&quot;layout-row&quot;]/vertical-menu-workflow-item-directive[1]/div[1]/button[@class=&quot;md-icon-button md-button md-ink-ripple md-focused&quot;]/md-icon[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>md-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>md-svg-icon</name>
      <type>Main</type>
      <value>plus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>plus</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialogContent_correspondence-workflow-popup&quot;)/div[1]/div[@class=&quot;layout-row flex&quot;]/md-content[@class=&quot;relative scrollable-element ps ps--theme_default _md layout-row flex&quot;]/div[@class=&quot;p20&quot;]/div[@class=&quot;layout-column flex&quot;]/div[@class=&quot;layout-row&quot;]/md-card[@class=&quot;card-overlay _md layout-column flex&quot;]/md-table-container[1]/table[@class=&quot;ng-pristine ng-untouched ng-valid md-table ng-not-empty md-row-select&quot;]/tbody[@class=&quot;md-body&quot;]/tr[@class=&quot;md-row&quot;]/td[@class=&quot;md-cell&quot;]/div[@class=&quot;layout-row&quot;]/vertical-menu-workflow-item-directive[1]/div[1]/button[@class=&quot;md-icon-button md-button md-ink-ripple md-focused&quot;]/md-icon[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//md-dialog-content[@id='dialogContent_correspondence-workflow-popup']/div/div/md-content/div/div/div[3]/md-card/md-table-container/table/tbody/tr/td[7]/div/vertical-menu-workflow-item-directive/div/button/md-icon</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تنبية عبر البريد الالكتروني'])[2]/following::md-icon[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تنبيه عبر الرسائل النصية'])[2]/following::md-icon[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='صفحة:'])[1]/preceding::md-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عدد الصفوف بالصفحة:'])[1]/preceding::md-icon[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//vertical-menu-workflow-item-directive/div/button/md-icon</value>
   </webElementXpaths>
</WebElementEntity>
